### ISSUE TITLE
Wijzigingsverzoek

### ISSUE THREAD

**Issue by BoazWelsenis** [TijnVdVelde/C2PRA#2]
- [x] Schroevendraaiers pagina toevoegen
- [x] Handzagen pagina toevoegen
- [x] Pagina over George Cloony maken

- [x] De pagina's over de zagen moeten worden gegroepeerd worden in losse supgroepen (onder gereedschap)

- [x] Nieuwe supgroep "Dranken" maken
- [x] Nieuwe supgroep “Frisdrank” maken
- [x] Nieuwe supgroep “Warme Dranken” maken

- [x] Oranje pagina met 3 frisdranken (Cola Up Sinas) maken
- [x] Paarse pagina met 3 warme dranken (Koffie Latte en Thee) maken

- [x] Onder koffie moet je kunnen doorklikken naar George Clooney
- [x] Onder Cola moet je kunnen doorklikken naar Roger Moore

**Comment by TijnVdVelde** [comment]
Is al opgelost
